# 数据库配置
spring:
  redis:
    database: 9
    host: 192.168.1.141
    port: 6378
    password: redis3.14159

jdevelops:
  # jwt
  jwt:
    token-secret: b4c33a6f172f13f91500b6c437a78d2cc5e5e9973e7dee431a1e8c34e68d365e
    web:
      interceptor:
#        exclude-path-patterns: [/**] # jwt放行接口
