# 基础配置
server:
  port: 9003


# 数据库配置
spring:
  redis:
    database: 2
    host: 127.0.0.1
    port: 8502
    password: 123456

jdevelops:
  # jwt
  jwt:
    token-secret: build
    web:
      interceptor:
#        exclude-path-patterns: [/**] # jwt放行接口
