spring:
  application:
    name: dal-jpa
  profiles:
    active: dev
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#        column_ordering_strategy: cn.tannn.jdevelops.jpa.table.FieldSequenceColumnOrderingStrategy
jdevelops:
  jpa:
    column:
#      order: alphabet
      order: field
  swagger:
    base-package: cn.tannn.jdevelops.demo.jpa
    security-scheme-default: false
