spring:
  application:
    name: dal-jpa
  profiles:
    active: dev
jdevelops:
  jpa:
    column:
#      order: alphabet
      order: field
  swagger:
    base-package: cn.tannn.jdevelops.demo.jpa
    security-scheme-default: false
