
# 七牛
jdevelops:
  oss:
    browse-url: https://s3.amazonaws.com/bucket
    aws3:
      # Access key就像用户ID，可以唯一标识你的账户。
      access_key: accessKey
      # Secret key是你账户的密码。
      secret_key: secretKey
      region-id: us-east-1
