
# minio\u914D\u7F6E
jdevelops:
  oss:
    # minio服务ip或者域名
    upload_url: ${MINIO_UPLOAD_URL:oss.xx.com}
    # minio服务端口或者代理端口
    port: ${MINIO_PORT:443}
    # 是否使用https
    https: ${MINIO_SECURE:true}
    # Access key就像用户ID，可以唯一标识你的账户。
    access_key: ${MINIO_ROOT_USER:xx}
    # Secret key是你账户的密码。
    secret_key: ${MINIO_ROOT_PASSWORD:xx}
    # 直接浏览地址，若有端口则加上端口
    browse_url: ${MINIO_BROWSE_URL:https://oss.xx.com}

  swagger:
    base-package: cn.jdevelops.file.controller
    add-header-token: false
