
# 七牛
jdevelops:
  oss:
    browse-url: https://oss.tannn.cn
    qiniu:
      # Access key就像用户ID，可以唯一标识你的账户。
      access_key: YCmVOUT8AYomla_PXmze0vBHHZ9H5cyh8BRnMMwf
      # Secret key是你账户的密码。
      secret_key: q3grIj1O4Za4Fvmbe7pu18i9-mq6DOiVeDuHUKQb
      https: true
      region-id: z2
