
# 七牛
jdevelops:
  oss:
    # Access key就像用户ID，可以唯一标识你的账户。
    access_key: access_key
    # Secret key是你账户的密码。
    secret_key: secret_key
    https: true
    browse-url: https://oss.tannn.cn
    region-id: z2

