springdoc:
  default-flat-param-object: true
# 默认是false（参数显示会有问题），需要设置为true
spring:
  profiles:
    active: local
jdevelops:
  swagger:
    base-package:
      - cn.jdevelops.file.controller
    security-scheme-default: false
knife4j:
  enable: true
  setting:
    language: zh-CN
    custom-code: 500
    enable-footer-custom: false
debug: true

