CREATE DATABASE  test_renewpwd ;

-- `public`.`test_demo` definition

-- Drop table

-- DROP TABLE `public`.`test_demo`;

CREATE TABLE `public`.`test_demo` (
      `id` integer NOT NULL GENERATED BY DEFAULT AS IDENTITY(1,1),
      `name` character varying(64 char) NOT NULL,
	CONSTRAINT `test_demo_pkey` PRIMARY KEY (id)
)TABLESPACE sys_default;



INSERT INTO `public`.`test_demo` (`id`, `name`) VALUES (1, '韦致远');
INSERT INTO `public`.`test_demo` (`id`, `name`) VALUES (2, '曹致远');
INSERT INTO `public`.`test_demo` (`id`, `name`) VALUES (3, 'Leonard Bell');
INSERT INTO `public`.`test_demo` (`id`, `name`) VALUES (4, '邹致远');
INSERT INTO `public`.`test_demo` (`id`, `name`) VALUES (5, '周杰宏');
INSERT INTO `public`.`test_demo` (`id`, `name`) VALUES (6, '郑秀英');
INSERT INTO `public`.`test_demo` (`id`, `name`) VALUES (7, 'Tammy Medina');
INSERT INTO `public`.`test_demo` (`id`, `name`) VALUES (8, '贺嘉伦');
INSERT INTO `public`.`test_demo` (`id`, `name`) VALUES (9, '金宇宁');
INSERT INTO `public`.`test_demo` (`id`, `name`) VALUES (10, 'Robin Wilson');
