spring:
  application:
    name: apis-idempotent
  data:
    redis:
      database: 9
      password: 123456
      port: 6379
      host: 127.0.0.1
jdevelops:
  idempotent:
    expire-time: 120000
    group-str: tannnn
    parameter-encryption: false
