spring:
  application:
    name: apis-idempotent
  redis:
    database: 9
    host: 127.0.0.1
    port: 6379
    password: 123456
jdevelops:
  idempotent:
    expire-time: 120000
    group-str: tannnn
    parameter-encryption: false
