# 基础配置
server:
  port: 9003


# 数据库配置
spring:
  redis:
    database: 2
    host: 127.0.0.1
    port: 8502
    password: 123456
  datasource:
    password: root
    username: root
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://127.0.0.1:3306/db_build?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Chongqing&allowPublicKeyRetrieval=true
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 120000 # 连接最大存活时间.不等于0且小于30秒，会被重置为默认值30分钟(1800000).设置应该比mysql设置的超时时间短
      maximum-pool-size: 15 # ((core_count * 2) + effective_spindle_count)
      pool-name: ${spring.application.name}
      minimum-idle: 15 # 和最大连接数保持一致
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  boot:
    admin:
      client:
        enabled: false
        url:
          - http://127.0.0.1:8001
        instance:
          service-url: http://127.0.0.1:${server.port} # 建议更换成真实IP
          name: ${spring.application.name}
          metadata:
            user.name: ${spring.security.user.name}
            user.password: ${spring.security.user.password}
#        username: admin端密码，如果放行可不配
#        password: admin端密码，如果放行可不配
  security:
    user:
      name: user
      password: passowrd
  # 监控
management:
  endpoints:
    web:
      exposure:
        include:
          - "*" # prometheus
        exclude:
          - shutdown
          - sessions
  metrics:
    tags:
      application: ${spring.application.name}
jdevelops:
  # jwt
  jwt:
    web:
      interceptor:
#        exclude-path-patterns: [/**] # jwt放行接口
