server:
  port: 8090

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  application:
    name: authorization-resource
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://127.0.0.1:9000
