spring:
  profiles:
    active: tn
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/demo_sas?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Chongqing&allowPublicKeyRetrieval=true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
server:
  port: 9000

---
spring:
  datasource:
    password: root
  config:
    activate:
      on-profile: dev
jdevelops:
  sas:
    token:
      reuse-refresh-tokens: true
---
spring:
  datasource:
    password: root
  config:
    activate:
      on-profile: tn

