spring:
  redis:
    database: 8
    host: 127.0.0.1
    port: 6379
    timeout: 2000
    password: 123456
jdevelops:
  idempotent:
    expire-time: 120000
    group-str: tannnn
    parameter-encryption: false
