# 数据库配置
spring:
  redis:
    database: 9
    host: 192.168.1.141
    port: 6378
    password: redis3.14159
jdevelops:
  idempotent:
    expire-time: 120000
    group-str: tannnn
    parameter-encryption: false
