spring:
  profiles:
    active: prod
#logging:
#  level:
#    root: error
#  org.springframework.boot: debug

---
spring:
  config:
    activate:
      on-profile: dev

jdevelops:
  api:
    result:
      enabled: false # \u9ED8\u8BA4fase


---
spring:
  config:
    activate:
      on-profile: prod

jdevelops:
  api:
    result:
      enabled: true

