server:
  ip: sso-client-order
  port: 8082

logging:
  level:
    org.springframework.security: trace

spring:
  application:
    name: spring-oauth-client-order
  security:
    oauth2:
      client:
        provider:
          #???????
          oauth-server:
            #????
            issuer-uri: http://127.0.0.1:9000
            authorizationUri: ${spring.security.oauth2.client.provider.oauth-server.issuer-uri}/oauth2/authorize
            #??????
            tokenUri: ${spring.security.oauth2.client.provider.oauth-server.issuer-uri}/oauth2/token
        registration:
          messaging-client-oidc:
            #?????????????????????????oauth-server????
            provider: oauth-server
            #?????
            client-name: web??-SSO???-????
            #???id????????????id
            client-id: web-client-id-order
            #?????
            client-secret: secret
            #???????
            client-authentication-method: client_secret_basic
            #????????????token?
            authorization-grant-type: authorization_code
            #??????????????code?????????????http://www.baidu.com??
            redirect-uri: http://192.168.1.71:8082/login/oauth2/code/messaging-client-oidc
            scope:
              - profile
              - openid
