jdevelops:
  jwt:
    token-secret: b4c33a6f172f13f91500b6c437a78d2cc5e5e9973e7dee431a1e8c34e68d365e
  websocket:
    multipart: true
    on-close: true
    verify-path-no: true


spring:
  redis:
    host: 192.168.0.65
    password: 123456
    port: 8502
    database: 1
    timeout: 2000
