jdevelops:
  jwt:
    expire-time: 100000
    token-secret: b4c33a6f172f13f91500b6c437a78d2cc5e5e9973e7dee431a1e8c34e68d365e
    web:
      interceptor:
        #  add-path-patterns: /**
        exclude-path-patterns: [/letGo,/letGo2,/login]
    cookie:
      cookie: true
    verify-platform: true
    oss:
      enable: true
#      oss-local-jwt-key: token
      verify-local-oss-resource-context-path: "jdevelops.oss.local.config.context-path"
      verify-local-oss-resource-up-dir: "jdevelops.oss.local.config.upload-dir"
  swagger:
    base-package: cn.tannn.demo.jdevelops.authenticationsjwt.controller
  oss:
    master: local_storage
    local:
      config:
        browse-url: http://127.0.0.1:8080
        upload-dir: H:/test/file
        context-path: /images
