

spring:
  application:
    name: jdevelops-config-demo

  datasource:
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test_standalone_config?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Chongqing&allowPublicKeyRetrieval=true
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 120000
      maximum-pool-size: 15
      pool-name: ${spring.application.name}
      minimum-idle: 15
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
jdevelops:
  config:
    app: app1
    env: dev
    ns: public


logging:
  level:
#    root: error
    cn.jdevelops.config: debug


