spring:
  redis:
    host: 127.0.0.1
    password: 123456
    port: 6379
    database: 1
    timeout: 2000

jdevelops:
  redis:
    event:
      pub:
        pattern-topic: # 频道名
          - tn
          - test
