springdoc:
# default  false（parameter abnormality），need setting true
  default-flat-param-object: true
knife4j:
  enable: true
  setting:
    language: zh-CN
    custom-code: 500
    enable-footer-custom: false


spring:
  profiles:
    active: dev
