server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  application:
    name: dynamicDatasourceSelector
  datasource:
    password: root
    username: root
    url:  jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Chongqing&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 120000
      maximum-pool-size: 15 # ((core_count * 2) + effective_spindle_count)
      pool-name: ${spring.application.name}
      minimum-idle: 15
jdevelops:
  swagger:
    base-package:
      - com.example.jdevelopsdataddssdemo.controller
    title: ${spring.application.name}
    security-scheme-default: false
#  dynamic:
#    table-name: dy_datasource_copy1

