server:
  port: 8090

spring:
  application:
    name: authorization-resource
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://127.0.0.1:9000

jdevelops:
  sas:
    # \u653E\u884C\u63A5\u53E3\uFF0C\u5176\u4ED6\u7684\u81EA\u5DF1\u770B\u4EE3\u7801\u6CE8\u91CA
    ant-matchers:
      - /hi
