springdoc:
  # default  false（parameter abnormality），need setting true
  default-flat-param-object: true
knife4j:
  enable: true
  setting:
    language: zh-CN
    custom-code: 500
    enable-footer-custom: false
jdevelops:
  swagger:
    base-package:
      - cn.tannn.springbootparentswagger.controller
      - cn.tannn.springbootparentswagger.api
#    security-scheme-default: false
    swagger-security-schemes:
      - {
          security: true,
          scheme:
            {
              in: HEADER,
              type: APIKEY,
              name: tokens,
            }
      }
      - {
        security: false,
        scheme:
          {
            type: OAUTH2,
            flows:{
              password:
                {
                  token-url: http://ballcat-admin:8080/oauth/token
                }
            }
          }
      }
debug: true
